version: '3'
networks:
    uniform: 
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
services:
    mariadb:
        container_name: mariadb
        image: mariadb:10.4
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            TZ: Asia/Shanghai
        volumes:
            - ./data/mysql5.7/data:/var/lib/mysql
            - ./mysql5.7/conf:/etc/my.cnf.d
            - ./data/mysql5.7/logs:/var/log/mariadb
        restart: always
        networks:
            uniform: 
                ipv4_address: 172.18.0.2
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        environment:
            TZ: Asia/Shanghai
        volumes:
            - /Users/simple.xull/DevOps/Code:/var/www/html
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf/conf.d:/etc/nginx/conf.d
            - ./data/nginx/logs:/var/log/nginx
        depends_on:
            - php
        restart: always
        networks:
            uniform: 
                ipv4_address: 172.18.0.3
    php:
        container_name: php
        build: ./php7
        ports: 
            - 9000:9000
        environment:
            TZ: Asia/Shanghai
        volumes:
            - /Users/simple.xull/DevOps/Code:/var/www/html
            - ./php7/conf/php.ini:/usr/local/etc/php/php.ini
            - ./php7/conf/php-fpm.conf:/usr/local/ect/php-fpm.conf
            - ./php7/conf/www/www.conf:/usr/local/etc/php-fpm.d/www.conf
        depends_on:
            - mariadb
            - redis
        restart: always
        networks:
            uniform: 
                ipv4_address: 172.18.0.4
    redis:
        container_name: redis
        image: redis:latest
        ports:
            - 6379:6379
        environment:
            TZ: Asia/Shanghai
        volumes:
            - ./data/redis/db:/var/lib/redis
            - ./data/redis/logs:/var/log/redis
        restart: always
        networks:
            uniform: 
                ipv4_address: 172.18.0.5